services:
  stt24-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stt24-app
    restart: unless-stopped
    ports:
      - "3005:80"
    environment:
      - NODE_ENV=production
